---
trigger:
- main

steps:
- checkout: self
  fetchDepth: 0

#Prepare analyse config
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'testgate'
    organization: 'mateusmantoanutf'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'mateusmantoanutf_mobile-app'
    cliProjectName: 'mobile-app'
    cliSources: '.'

#Build step
- task: Xcode@5
  inputs:
    actions: 'test'
    configuration: 'Release'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 
    packageApp: false

- task: SonarCloudAnalyze@1
